[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "I", "T20", "B"]
extend-select = ["A", "D"]

[tool.ruff.format]
quote-style = "double"
docstring-code-format = true
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"
